sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t react-test ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm test

after_success:
  - docker build -t alvaro2598/multi-client ./client
  - docker build -t alvaro2598/multi-nginx ./nginx
  - docker build -t alvaro2598/multi-server ./server
  - docker build -t alvaro2598/multi-worker ./worker
  #Log in into docker CLI
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images an push them into docker hub
  - docker push alvaro2598/multi-client
  - docker push alvaro2598/multi-nginx
  - docker push alvaro2598/multi-server
  - docker push alvaro2598/multi-worker
